# Generated by Django 4.2.6 on 2023-12-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_No', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=4)),
                ('std_class', models.CharField(max_length=10)),
                ('stream', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=20)),
            ],
        ),
    ]
