# Generated by Django 4.2.6 on 2023-12-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('BOT', models.PositiveIntegerField()),
                ('MOT', models.PositiveIntegerField()),
                ('EOT', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('grade', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=20)),
                ('totalmarks', models.PositiveIntegerField()),
                ('averagemarks', models.PositiveIntegerField()),
            ],
        ),
    ]
