# Generated by Django 4.2.6 on 2023-12-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOS', '0002_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_class', models.CharField(max_length=20)),
                ('stream', models.CharField(max_length=30)),
                ('aggregates', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
