# Generated by Django 4.2.6 on 2023-12-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOS', '0005_alter_position_std_no_alter_reportcard_std_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='theme',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
