# Generated by Django 4.2.6 on 2023-12-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOS', '0007_alter_position_division_alter_position_std_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='std_class',
            field=models.CharField(choices=[('P1', 'P.1'), ('P2', 'P.2'), ('P3', 'P.3'), ('P4', 'P.4'), ('P5', 'P.5'), ('P6', 'P.6'), ('P7', 'P.7')], max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='stream',
            field=models.CharField(choices=[('EAST', 'A'), ('WEST', 'B')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_class',
            field=models.CharField(choices=[('P1', 'P.1'), ('P2', 'P.2'), ('P3', 'P.3'), ('P4', 'P.4'), ('P5', 'P.5'), ('P6', 'P.6'), ('P7', 'P.7')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('EAST', 'A'), ('WEST', 'B')], max_length=20),
        ),
    ]
